# Generated by Django 5.0.4 on 2024-04-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('registration_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('car_number_in', models.CharField(max_length=16)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('car_number_out', models.CharField(blank=True, max_length=16, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspace')),
                ('photo_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_photo_in', to='photos.photo')),
                ('photo_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_photo_out', to='photos.photo')),
            ],
        ),
    ]
