# Generated by Django 5.0.4 on 2024-04-14 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tariff',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='registration_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_photo_in', to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_photo_out', to='photos.photo'),
        ),
    ]
