# Generated by Django 5.0.4 on 2024-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_parkingspace_user_remove_registration_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
