# Generated by Django 5.0.4 on 2024-04-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_parkingspace_registration_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('car_number_in', models.CharField(max_length=16)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspace')),
            ],
        ),
        migrations.CreateModel(
            name='ExitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_datetime', models.DateTimeField()),
                ('car_number_out', models.CharField(max_length=16)),
                ('entry_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.entryregistration')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspace')),
            ],
        ),
        migrations.CreateModel(
            name='CombinedRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.entryregistration')),
                ('exit_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.exitregistration')),
            ],
        ),
    ]
