# Generated by Django 5.0.4 on 2024-04-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_entryregistration_exitregistration_and_more'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryregistration',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='exitregistration',
            name='entry_registration',
        ),
        migrations.RemoveField(
            model_name='exitregistration',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='reserved',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='registration_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo'),
        ),
        migrations.DeleteModel(
            name='CombinedRegistration',
        ),
        migrations.DeleteModel(
            name='EntryRegistration',
        ),
        migrations.DeleteModel(
            name='ExitRegistration',
        ),
    ]
