# Generated by Django 5.0 on 2024-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_entryregistration_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='tariff_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
