# Generated by Django 5.0.4 on 2024-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_registration_tariff_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='car_num',
            field=models.CharField(default='', max_length=16),
        ),
    ]
