# Generated by Django 5.0.4 on 2024-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_remove_payment_user_id_alter_payment_registration_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
