# Generated by Django 5.0.4 on 2024-04-23 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_tariff_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59)),
        ),
    ]
