# docker-compose  --file docker-compose-project.yml --env-file .env_prod  up -d 
version: "3.8"
name: fastparking
services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #expose:
    #  - "${POSTGRES_PORT}"
    ports:
       - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ../database/postgres-data:/var/lib/postgresql/data

  code :
    build: ../FRONTEND
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
     depends_on:
      - pg
 
