# Generated by Django 5.0.4 on 2024-04-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_displayed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
