# Generated by Django 5.0.4 on 2024-04-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycars',
            name='car_number',
        ),
    ]
