# Generated by Django 5.0.4 on 2024-04-13 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_mycars_car_number'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycars',
            name='car_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car'),
        ),
    ]
