# Generated by Django 5.0 on 2024-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mycars_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycars',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mycars',
            name='car_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
