# Generated by Django 5.0.4 on 2024-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cars',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
