# Generated by Django 5.0.4 on 2024-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_photo_car_photo_car_car_paypass_car_blocked'),
        ('users', '0002_remove_customuser_cars_customuser_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cars',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='owners', to='cars.car'),
        ),
    ]
