# Generated by Django 5.0.4 on 2024-04-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
