# Generated by Django 5.0.6 on 2024-05-26 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_cars_customuser_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must start with '+' followed by digits.",
                        regex="^(\\+\\d+)$",
                    ),
                    django.core.validators.MinLengthValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telegram_nickname",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telegram nickname must start with '@' followed by letters or digits, or '+' followed by digits.",
                        regex="^(@[\\w\\d]+|\\+\\d+)$",
                    )
                ],
            ),
        ),
    ]
