# Generated by Django 5.0.4 on 2024-04-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_cars_customuser_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
