# Generated by Django 5.0.4 on 2024-04-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_custom_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_field_name',
        ),
    ]
