# Generated by Django 4.2.6 on 2024-04-24 16:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_telegram_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[users.models.validate_unique_telegram_nickname]),
        ),
    ]
