# Generated by Django 5.0.4 on 2024-04-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=16, null=True)),
                ('predict', models.FloatField(null=True)),
                ('PayPass', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('photo_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo')),
            ],
        ),
    ]
