# Generated by Django 5.0.4 on 2024-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo',
            new_name='photo_car',
        ),
        migrations.AddField(
            model_name='car',
            name='PayPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
