# Generated by Django 5.0.4 on 2024-04-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pay_pass',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo_car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='predict',
            field=models.FloatField(null=True),
        ),
    ]
