# Generated by Django 5.0.4 on 2024-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_photo_car_photo_car_car_paypass_car_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
