# Generated by Django 5.0 on 2024-04-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_mycars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCars',
        ),
    ]
