# Generated by Django 5.0.6 on 2024-05-15 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_delete_mycars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=32)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("UNDEFINED", 1),
                            ("CAR", 2),
                            ("USER", 3),
                            ("REGISTRATION", 4),
                        ],
                        default="UNDEFINED",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDEFINED", 1),
                            ("BLOCKED", 2),
                            ("UNBLOCKED", 3),
                            ("PASSED", 4),
                            ("UNPASSED", 5),
                            ("DELETED", 6),
                            ("REPLACED", 7),
                            ("ARCHIVED", 8),
                        ],
                        default="UNDEFINED",
                    ),
                ),
                ("comment", models.TextField(max_length=255)),
                ("username", models.CharField(max_length=32)),
                ("location", models.CharField(blank=True, max_length=32, null=True)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
