# Generated by Django 5.0.6 on 2024-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("UNDEFINED", "UNDEFINED"),
                    ("CAR", "CAR"),
                    ("USER", "USER"),
                    ("REGISTRATION", "REGISTRATION"),
                ],
                default="UNDEFINED",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDEFINED", "UNDEFINED"),
                    ("BLOCKED", "BLOCKED"),
                    ("UNBLOCKED", "UNBLOCKED"),
                    ("PASSED", "PASSED"),
                    ("UNPASSED", "UNPASSED"),
                    ("DELETED", "DELETED"),
                    ("REPLACED", "REPLACED"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="UNDEFINED",
            ),
        ),
    ]
